# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import frame as module_0


def test_case_0():
    int_0 = 671
    with pytest.raises(TypeError):
        module_0.ReferenceFrame(int_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    module_0.CoordinateSym()


def test_case_2():
    str_0 = "\\N@4s|JKk\t&,-"
    with pytest.raises(TypeError):
        module_0.ReferenceFrame(str_0, str_0, str_0)


def test_case_3():
    str_0 = "\\N\\@4Es|JKk\t&|,\t"
    with pytest.raises(TypeError):
        module_0.ReferenceFrame(str_0, latexs=str_0, variables=str_0)


def test_case_4():
    str_0 = "\\p\\P40|JKk\t&|d-"
    with pytest.raises(TypeError):
        module_0.ReferenceFrame(str_0, variables=str_0)


@pytest.mark.xfail(strict=True)
def test_case_5():
    str_0 = "0s'\r]Qd/JT>}^RX"
    module_0.ReferenceFrame(str_0)


def test_case_6():
    str_0 = "\\p\\P40|Jk\t&|-"
    tuple_0 = ()
    with pytest.raises(ValueError):
        module_0.ReferenceFrame(str_0, tuple_0)


def test_case_7():
    str_0 = "\\p\\P40|Jk\t&|-"
    tuple_0 = ()
    with pytest.raises(ValueError):
        module_0.ReferenceFrame(str_0, latexs=tuple_0)


def test_case_8():
    str_0 = "&t3\tzT"
    tuple_0 = ()
    with pytest.raises(ValueError):
        module_0.ReferenceFrame(str_0, variables=tuple_0)


@pytest.mark.xfail(strict=True)
def test_case_9():
    str_0 = "\r6tqgI"
    list_0 = [str_0, str_0, str_0]
    module_0.ReferenceFrame(str_0, list_0, list_0)


@pytest.mark.xfail(strict=True)
def test_case_10():
    str_0 = "DdPs?[HFr`LYg@"
    list_0 = [str_0, str_0, str_0]
    module_0.ReferenceFrame(str_0, variables=list_0)
