# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import sympy.physics.mechanics.kane as module_0
import sympy.matrices.dense as module_1


def test_case_0():
    int_0 = 438
    with pytest.raises(TypeError):
        module_0.KanesMethod(
            int_0,
            int_0,
            int_0,
            velocity_constraints=int_0,
            acceleration_constraints=int_0,
            u_auxiliary=int_0,
            forcelist=int_0,
        )


def test_case_1():
    none_type_0 = None
    with pytest.raises(TypeError):
        module_0.KanesMethod(
            none_type_0, none_type_0, none_type_0, u_auxiliary=none_type_0
        )


@pytest.mark.xfail(strict=True)
def test_case_2():
    module_1.eye()
