# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import sympy.physics.mechanics.joint as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    str_0 = "`G"
    module_0.SphericalJoint(str_0, str_0, str_0, parent_point=str_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    module_0.PinJoint(
        none_type_0,
        none_type_0,
        none_type_0,
        parent_interframe=none_type_0,
        child_axis=none_type_0,
        joint_axis=none_type_0,
    )


@pytest.mark.xfail(strict=True)
def test_case_2():
    none_type_0 = None
    module_0.PrismaticJoint(
        none_type_0,
        none_type_0,
        none_type_0,
        parent_point=none_type_0,
        parent_joint_pos=none_type_0,
    )


@pytest.mark.xfail(strict=True)
def test_case_3():
    none_type_0 = None
    module_0.CylindricalJoint(
        none_type_0,
        none_type_0,
        none_type_0,
        none_type_0,
        child_point=none_type_0,
        joint_axis=none_type_0,
    )


@pytest.mark.xfail(strict=True)
def test_case_4():
    none_type_0 = None
    module_0.PlanarJoint(
        none_type_0,
        none_type_0,
        none_type_0,
        planar_coordinates=none_type_0,
        rotation_speed=none_type_0,
    )


@pytest.mark.xfail(strict=True)
def test_case_5():
    float_0 = -261.739
    module_0.SphericalJoint(
        float_0, float_0, float_0, float_0, child_point=float_0, rot_order=float_0
    )


@pytest.mark.xfail(strict=True)
def test_case_6():
    none_type_0 = None
    module_0.WeldJoint(
        none_type_0, none_type_0, none_type_0, child_interframe=none_type_0
    )
